project_name: seki

before:
  hooks:
    - make freeze

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    mod_timestamp: "{{ .CommitTimestamp }}"

dockers:
  - use: buildx
    goos: linux
    goarch: amd64
    image_templates:
      - ghcr.io/oscarbc96/{{ .ProjectName }}:{{ .Version }}-amd64
      - ghcr.io/oscarbc96/{{ .ProjectName }}:latest-amd64
    build_flag_templates:
      - --platform=linux/amd64
      - --label=org.opencontainers.image.title={{ .ProjectName }}
      - --label=org.opencontainers.image.url={{ .GitURL }}
      - --label=org.opencontainers.image.source={{replace .GitURL ".git" "" }}
      - --label=org.opencontainers.image.version={{ .Version }}
      - --label=org.opencontainers.image.created={{ .CommitDate }}
      - --label=org.opencontainers.image.revision={{ .FullCommit }}
  - use: buildx
    goos: linux
    goarch: arm64
    image_templates:
      - ghcr.io/oscarbc96/{{ .ProjectName }}:{{ .Version }}-arm64v8
      - ghcr.io/oscarbc96/{{ .ProjectName }}:latest-arm64v8
    build_flag_templates:
      - --platform=linux/arm64/v8
      - --label=org.opencontainers.image.title={{ .ProjectName }}
      - --label=org.opencontainers.image.url={{ .GitURL }}
      - --label=org.opencontainers.image.source={{replace .GitURL ".git" "" }}
      - --label=org.opencontainers.image.version={{ .Version }}
      - --label=org.opencontainers.image.created={{ .CommitDate }}
      - --label=org.opencontainers.image.revision={{ .FullCommit }}

docker_manifests:
  - name_template: ghcr.io/oscarbc96/{{ .ProjectName }}:{{ .Version }}
    image_templates:
      - ghcr.io/oscarbc96/{{ .ProjectName }}:{{ .Version }}-amd64
      - ghcr.io/oscarbc96/{{ .ProjectName }}:{{ .Version }}-arm64v8
  - name_template: ghcr.io/oscarbc96/{{ .ProjectName }}:latest
    image_templates:
      - ghcr.io/oscarbc96/{{ .ProjectName }}:latest-amd64
      - ghcr.io/oscarbc96/{{ .ProjectName }}:latest-arm64v8
