name: test

on: pull_request

permissions:
  contents: read

jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: 1.18

      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Generate Support Files
        run: make generate

      - name: Tests
        run: make test
