name: test

on: pull_request

permissions:
  contents: read

jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: 1.19

      - run: go install gotest.tools/gotestsum@latest

      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Tests
        run: make test

      - name: Check it can compile
        uses: goreleaser/goreleaser-action@v3
        with:
          args: build --snapshot --rm-dist --single-target
