name: test

on: [push, pull_request]

permissions:
  contents: read

jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: 1.18

      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - run: go get -u github.com/kyoh86/richgo

      - name: Tests
        run: make test
        env:
          RICHGO_FORCE_COLOR: 1
